import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import usersRouter from "./users";
import rolesRouter from "./roles";
import permissionsRouter from "./permissions";
import auditRouter from "./audit";
import catalogRouter from "./catalog";
import warehousesRouter from "./warehouses";
import productsRouter from "./products";
import inventoryRouter from "./inventory";
import treasuryRouter from "./treasury";
import customersRouter from "./customers";
import suppliersRouter from "./suppliers";
import salesRouter from "./sales";
import purchasesRouter from "./purchases";
import financeRouter from "./finance";
import dashboardRouter from "./dashboard";
import reportsRouter from "./reports";
import settingsRouter from "./settings";
import notificationsRouter from "./notifications";
import inventoryOpsRouter from "./inventory-ops";
import associationsRouter from "./associations";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(usersRouter);
router.use(rolesRouter);
router.use(permissionsRouter);
router.use(auditRouter);
router.use(catalogRouter);
router.use(warehousesRouter);
router.use(productsRouter);
router.use(inventoryRouter);
router.use(treasuryRouter);
router.use(customersRouter);
router.use(suppliersRouter);
router.use(salesRouter);
router.use(purchasesRouter);
router.use(financeRouter);
router.use(dashboardRouter);
router.use(reportsRouter);
router.use(settingsRouter);
router.use(notificationsRouter);
router.use(inventoryOpsRouter);
router.use(associationsRouter);

export default router;
