// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/pos-system/Dashboard.tsx": () => import("../components/mockups/pos-system/Dashboard.tsx"),
  "./components/mockups/pos-system/Inventory.tsx": () => import("../components/mockups/pos-system/Inventory.tsx"),
  "./components/mockups/pos-system/POS.tsx": () => import("../components/mockups/pos-system/POS.tsx")
};
